title: ChicagoML
baseurl: '/'
url: 'https://chicago.ml'
permalink: pretty
exclude:
  - artwork
  - node_modules
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - LICENSE*.txt
  - lib/
  - README.md
  - contributors.md
search_enabled: true
future: true
excerpt_separator: <!--more-->
badge_colors:
  - green
  - yellow
  - blue
  - red
  - purple
aux_links:
  - name: GitHub
    url: 'https://github.com/gar1t/ChicagoML'
    icon_class: 'fab fa-github'
  - name: Slack
    url: https://bit.ly/2S0zFAP
    icon_class: 'fab fa-slack-hash'
